[project]
name = "3-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "basedpyright>=1.36.0",
    "flask>=3.1.2",
    "pydantic>=2.12.5",
]
